# Generated by Django 3.1.5 on 2021-01-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210110_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='image/NoImage.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
